version: "3.3"

services:

  hugo-build:
    image: klakegg/hugo:pandoc
    name: notes-build
    volumes: 
      - ".:/src"
    ports:
      - "1313:1313"

  hugo-server:
    image: klakegg/hugo:pandoc
    name: notes-server
    command: server
    volumes: 
      - ".:/src"
    ports:
      - "1313:1313"